insert into Events values(0,'#free food','Being back at school is so dreary, right? Well, not today from 12 -1 in the Lerner Piano Lounge it isnt! Come to Live at Lerners latest Sounds event for: The band: Bowmont, a Brooklyn band which is like a punchier Coldplay, but more fun. The food: Pita, baba ghanoush, hummus, falafel and more noms.','26-MAR-13', image(11, 'event img', 'event1.png'));


insert into Events values(1,'Liver at Lerner: Bowmont','om nom nom Tonight from 8-10 pm in 414 Pupin, you can snag some free pizza at CU Amnesty Internationals panel: Students vs. Teachers: the Right Paradigm for Education Reform? A panel discussion featuring Professor Jeffrey Henig of Teachers College, Wayne Wilson of Students for Education Reform, Alexander Donovan of Teach for America, and Mike Rady of Columbias Education Umbrella. The discussion will compare competing philosophies of education reform, addressing big issues which cities and states face in confronting the achievement gap in urban K-12 public schools. Topics will include performance pay for teachers, testing of student achievement, and the role of charter schools. The panel will conclude with an audience QandA. Sounds tasty interesting. Pizza pie via Wikimedia','12-MAR-13', image(12, 'event img', 'event2.png'));


insert into Events values(2,'Free Food at CU Amnesty International’s Panel','Green and a microphone  get it!? Tonight at 9pm, Greenborough is partnering with Barnard Columbia Divest for their biannual open mic night! BCD leaders will be giving a brief overview of what theyre working on before the performances start. Its sure to be an interesting and fun way to spend the evening! If you are interested in environmental action, good music, or tasty food make sure to check it out!       An easy solution via Shutterstock','9-MAR-13', image(13, 'event img', 'event3.png'));


insert into Events values(3,'Greenborough Open Mic Night!','Jinkies! Amnesty International is having a general body meeting at 9 pm tonight in Earl Hall with free food. What type, we dont know, but mystery makes life more exciting. Just dont subject your body to JJs again. It begs you.   The great food detective via Shutterstock','27-FEB-13', image(14, 'event img', 'event4.png'));


insert into Events values(4,'Free the Food!','Today at noon you could decide to leave your midterms and papers behind for a glorious life as a radical hobo OR you could head to the Live at Lerners Sounds #8, in the Lerner Piano Lounge from 12-1pm where there will be:  A band: Tumbling Bones. Think hoedown. Greek food: Rice pilaf, keftedes (meatballs with yogurt dip), greek salad An opportunity: Register for Columbia Community Outreach which will take place this year on 4/6/13','26-FEB-13', image(15, 'event img', 'event5.png'));


insert into Events values(5,'Live at Lerner: Tumbling Bones','Good job guys  Last night at their weekly meeting,Maren Killackey was impressed by CCSC. For once, there is no snark. No cheap shots, no embarrassing quotes, or slight misinformation because, lets face it, no one cares. Before descending into a sappy metaphor about some particularly efficient student government meeting (is there anything more sad?), Ill leave it at yesterdays meeting was everything a CCSC meeting should be. Period. EcoReps stopped by to present on its bike share pilot program, which theyve been working on for the past few years. After issuing a student interest survey last semester, they realized theres huge demand among students for such a program. Although they launched a very small scale pilot last spring, the project was just marginally successful, especially since there were only 8 janky bikes and it rained. This year theyre partnering with various bike share contractors around the city to provide a selected number of students 16 or so bikes to use at their leisur','25-FEB-13', image(16, 'event img', 'event6.png'));


insert into Events values(6,'CCSC: Bikes, Penetration, Bagels, WTF?','This is not study abroad Are you a SEAS student who wants to learn more about Study Abroad? Do you just want free pizza tonight? If yes, stop by 825 Mudd tonight at 8 PM and your needs will be quenched. The meeting will cover all the logistics of engineering study abroad, as well as any other questions attendees may have. There will also be free pizza from Che Bella. What the future holds for study abroaders via Shutterstock','18-FEB-13', image(17, 'event img', 'event7.png'));


insert into Events values(7,'Free Food: OverSEAS','A weeks worth of free food is pretty awesome The opening ceremony for Engineering Week will take place in Roone Arledge at 6 pm tonight, and there will be a bunch of food from Thai Market that apparently cost someone $2,000 but will cost $0 for you! There will be free food and free T-Shirts throughout the week in celebration of engineering at Columbia and around the nation!  The weeks schedule after the jump','17-FEB-13', image(18, 'event img', 'event8.png'));


insert into Events values(8,'Free Food for Engineering Week','AwwwColumbia DOES care! Sometimes dont you just feel like Columbia is showering you with love? Okay, okay, so its more like grudging acceptance but you take what you can get, right? Well, today Columbia is bursting with free candy and Valentines goodies! The Columbia Queer Alliance will be handing out free candy on College Walk today from 11 to 1 And the candy bonanza doesnt stop there! On the Lerner ramps from 2 to 4 PM, your CSA peer advisors will be giving out free candy wrapped with words of advice and encouragement! You can go eat some sugary treats and, for probably the only time ever, you can feel like Columbia actually loves gives a shit about you! Adorbs campus lovin via Shutterstock','14-FEB-13', image(19, 'event img', 'event9.png'));


insert into Events values(9,'Free Candy Bonanza!','These artsy posters arent for nuthin  How to start your Wednesday afternoon:  Go to the Lerner Piano Lounge between 12 and 1 pm for Live at Lerners Sounds event. Place pork pot stickers, fried rice, and fortune cookies directly in your mouth. Chew. Swallow. Soak up VensaireLive at Lerner calls them a little bit Animal Collective-y, and their Facebook notes their instinctelectual genre. Go to your 1:10 class.  As always, if you want to carefully craft your Wednesday schedule sooner, Live at Lerner has a niftyFacebook page announcing these events (so like it, if you want) and an events pagelisting who will be playing when (hint: its almost always every other Wednesday at noon). Also, theyve got some artsy signs plastered around campus. Heres a preview of todays act, but dont watch it if you shouldnt see strobe lights.  Poster via Live at Lerner','13-FEB-13', image(20, 'event img', 'event10.png'));


insert into Events values(10,'Live at Lerner: Vensaire','I dont know, this cake is pretty sexy just the way it is  The Culinary Society is holding their erotic cake competition tonight from 9 -10 in Lerner West Ramp Lounge. Come for a taste and vote for your favorite! Cake of beauty via Wikimedia','12-FEB-13', image(21, 'event img', 'event11.png'));


insert into Events values(11,'Culinary Society’s Erotic Cake Competition Tonight','Dear Friends/Foes, Loving the crew. You may claim that early midterms take precedent in planning your mid-week outings, but we know where yourpriorities truly lie: attendingThe Blue and White meeting this fine eve. Come over to the basement ofSt. Pauls Chapelat9 pmto pitch content for the March issue, enjoy some hotpizza, and ponder destiny with our lovely staff. If youre new, we want you. Ideas, criticisms, and coherent sentences are encouraged. With Love, The Editors','8-MAR-13', image(22, 'event img', 'event12.png'));


insert into Events values(12,'We Know You’re Tryna Hang','Does this song remind you of every middle school dance ever? Well come relive your middle school days at Bwog as we reminisce on middle school dance classics such as Whine Up,Umbrella,Get Low(clean version), Promiscuous and many more. SGO on the 5th floor of Lerner, 7 pm is where and when its at, so come and bring your ideas.  Would rather go to a 2006/2007 middle school dance than 1020 or Mels via Youtube','10-FEB-13', image(23, 'event img', 'event13.png'));


insert into Events values(13,'Bwog Meeting Tonight','The love of antiquity Tonights Valentines Day Mixer, hosted by CU Admirers, actually advertises itself as Wiens first party, so thats not us trying to be funny. Were just reporting the facts, and the apparent free cupcakes, cookies, and other sweet pink-and-red festooned foods that will be available tonightalong with a shot at true love, if the impassioned event description is to be believed.  Tonight from 9 to 11 in the Wien lounge, youre encouraged by all and sundry to dramatically ask out your crush (to Wien) and from there seduce them with card-making sessions and cupcakes of unknown provenance. A Valentines Day game show is also advertised; this all seems like a harrowing ordeal, but also maybe a fun one? Of course, if youre looking for love in a less direct manner you can always send in a Bwog personal. Love, Bwog Your secret admirer A classy lady via Wikimedia Commons','8-FEB-13', image(24, 'event img', 'event14.png'));


insert into Events values(14,'Wien Is Having Its First Party Ever','that samosas are yummy Delta GDP, the Growth and Development Project at Columbia, will meet tonight at 8:30 pm in Hamilton 303 for an open dialogue on womens rights in India. As youre eating your free samosas, discuss with peers the recent rape and murder of Jyothi Singh Pandey, Indias general attitude on the issue, and the future of womens rights in the developing world. Engage your taste buds and your cortex. Event poster via Delta GDP','6-FEB-13', image(25, 'event img', 'event15.png'));


